# -*- coding: utf-8 -*-
"""projetofinalia

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q5wKaSeRVXN54hxBoAQKkYSn99doti4x
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.utils import resample

import kagglehub
import os
import glob

path = kagglehub.dataset_download("crainbramp/steam-dataset-2025-multi-modal-gaming-analytics")
search_path = os.path.join(path, "**", "applications.csv")
files_found = glob.glob(search_path, recursive=True)

dir = os.path.dirname(files_found[0])
print(f"Diretório base dos CSVs identificado: {dir}")

df = pd.read_csv(os.path.join(dir, "applications.csv"))

df.head()

cols_to_fix = ['required_age', 'mat_final_price', 'mat_achievement_count']

for col in cols_to_fix:
    print(f"Limpando coluna: {col}...")
    df[col] = pd.to_numeric(df[col], errors='coerce')

df = df.dropna(subset=['mat_currency'])
moeda_principal = df['mat_currency'].mode()[0]
print(f"Filtrando dataset para usar apenas a moeda: {moeda_principal}")
df_clean = df[df['mat_currency'] == moeda_principal].copy()

features_cols = [
    'mat_final_price',
    'mat_achievement_count',
    'is_free',
    'mat_supports_windows',
    'mat_supports_mac',
    'mat_supports_linux',
    'required_age'
]

X = df_clean[features_cols].fillna(0)

bool_cols = ['is_free', 'mat_supports_windows', 'mat_supports_mac', 'mat_supports_linux']
for col in bool_cols:
    X[col] = X[col].astype(int);

threshold = df_clean['recommendations_total'].median();
y = np.where(df_clean['recommendations_total'] > threshold, 1, 0);

print(f"Definição de Sucesso: Mais de {threshold} recomendações.");
print(f"Total de instâncias limpas e prontas: {len(X)}");

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42);

scaler = StandardScaler();
X_train_scaled = scaler.fit_transform(X_train);
X_test_scaled = scaler.transform(X_test);

print("\nTreinando Random Forest...");
rf = RandomForestClassifier(n_estimators=100, random_state=42);
rf.fit(X_train, y_train);
y_pred_rf = rf.predict(X_test);

print("Treinando MLP (Rede Neural)...");
mlp = MLPClassifier(hidden_layer_sizes=(64, 32), max_iter=1000, random_state=42);
mlp.fit(X_train_scaled, y_train);
y_pred_mlp = mlp.predict(X_test_scaled);

def plot_confusion_matrix(y_test, y_pred, title):
    cm = confusion_matrix(y_test, y_pred);
    plt.figure(figsize=(5, 4));
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False);
    plt.xlabel('Previsto (0=Nicho, 1=Popular)');
    plt.ylabel('Real (0=Nicho, 1=Popular)');
    plt.title(title);
    plt.show();

print("\n--- RELATÓRIO: RANDOM FOREST ---");
print(classification_report(y_test, y_pred_rf));
plot_confusion_matrix(y_test, y_pred_rf, "Matriz de Confusão - Random Forest");

print("\n--- RELATÓRIO: MLP (REDE NEURAL) ---");
print(classification_report(y_test, y_pred_mlp));
plot_confusion_matrix(y_test, y_pred_mlp, "Matriz de Confusão - MLP");

plt.figure(figsize=(8, 5));
feature_importances = pd.Series(rf.feature_importances_, index=features_cols);
feature_importances.sort_values().plot(kind='barh');
plt.title("O que define a popularidade de um jogo? (Random Forest)");
plt.show();